### ISSUE TITLE
Opening drawer is slow when in lots of rooms

### ISSUE THREAD

**Issue by megamattron** [rogozhnikoff/rn-breakerapp#3]
I'm a bit of an extreme example because I'm in 200+ rooms, but it's currently very slow to open the drawer.

**Comment by rohozhnikoff** [comment]
same reasons from https://github.com/rogozhnikoff/rn-breakerapp/issues/4#issuecomment-240515569

and yes, big lists always bad for memory and layout
in https://github.com/rogozhnikoff/rn-breakerapp/issues/2 i will reimplement them with ListView
